### ISSUE TITLE
Compatibility with 3.0.x

### ISSUE THREAD

**Issue by Gumis91** [eurailcom/redmine_default_subtask_tracker#2]
Hi!
Great plugin. I'm happy to inform that code is working flawlessly on my heavily modded installation of Redmine 3.0.7.

On the bottom line, I'd love to have such settings not only for entire project, but also for each role.

**Comment by danielvijge** [comment]
Great to hear that it works on 3.0.x
As for the roles, you could try another plugin: [Redmine Track Control](https://github.com/jijeshmohan/redmine_track_control) This allows you to set which role can create which tracker type. But it works per role only, not per project. But smartly combining these two plugins should allow you to do what you need.

**Comment by Gumis91** [comment]
Thanks, I will definitely check out this plugin.

**Comment by danielvijge** [comment]
Fixed with ec5ff002bcd636bf809f37489d128b8176324fbe
